version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    depends_on:
      - mysql_server
    restart: always
    environment:
      - NODE_ENV=prod
    env_file:
      - ./.env.prod

  mysql_server:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=thieulamtu
